name: IndyCar secrets
run-name: IndyCar Driver App 🚀
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Download zipped photos from Google Drive 📂
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip unzip
          pip install gdown
          gdown https://drive.google.com/uc?id=${{ secrets.GDRIVE_FILE_ID }} -O photos.zip
          unzip photos.zip -d ./src/Photos
        env:
          GDRIVE_FILE_ID: ${{ secrets.GDRIVE_FILE_ID }}

      - name: Build 🔧
        run: npm run build -- --mode production

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages

      - name: Remove photos from gh-pages branch
        run: |
          git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages
          cd gh-pages
          rm -rf Photos
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Remove photos after deployment"
          git push
